### ISSUE TITLE
Extension doesn't work properly under VSCode 1.64 and Windows

### ISSUE THREAD

**Issue by rodigu** [denoland/vscode_deno#620]
**Describe the bug**

ts(2691) error coming up, even with Deno VSCcode extension installed and running in the workspace.

**To Reproduce**

1. Install Deno Extension
2. Run Deno Init
3. Open TS file
4. Import with .ts at the end

**Expected behavior**

Before (just yesterday) this error wouldn't show up because Deno recognized the .ts and suppressed the default  VSCode TS language feature.

**Screenshots**

![image](https://user-images.githubusercontent.com/58960796/152442828-929da374-5ae6-4433-b785-36b0b9ba65ff.png)

**Versions**

vscode: 1.64.0 deno:  1.18.1 extension: v3.10.1

**Comment by bartlomieju** [comment]
Does this error persist if you restart (or reload a window) VSCode?

**Comment by rodigu** [comment]
Yes.

It also persists after restarting the TS language features and the Deno extension, and also after uninstalling and resinstalling the extension.

**Comment by dsherret** [comment]
I didn't have any issue, but I restarted my vscode to update to vscode 1.64.0 and now also get this error.

**Comment by kitsonk** [comment]
I'm investigating.

**Comment by kitsonk** [comment]
@rodigu what OS are you using VScode on?

**Comment by rodigu** [comment]
I am using Windows.

**Comment by kitsonk** [comment]
Ok, it looks like something changed in VSCode 1.64 but is limited to Windows.  OSX and Linux don't appear to have the problem.

**Comment by rodigu** [comment]
oh I see 😞 
Thank you for checking it out

**Comment by kitsonk** [comment]
@dsherret has investigated and it looks like it is an issue with vscode itself when a language server plugin is used with vscode 1.64, and is supplying the built-in TypeScript language server with a location of the plugins.  vscode_deno uses a plugin to "mute" built-in diagnostics when the project is deno enabled, and that plugin is not starting under VSCode 1.64 under Windows because the path being supplied is invalid.

**Comment by kitsonk** [comment]
Ref: microsoft/vscode#142139

**Comment by rodigu** [comment]
Is there a quick fix for this?
For now, I am having to disable VSCode's TS features.

**Comment by dsherret** [comment]
I don’t think so because the issue is right before vscode passes a path to ts server. I think lots of extensions will be broken and more people will notice this shortly so hopefully they do a release soon. In the meantime I’d recommend downgrading to VS Code 1.63 https://code.visualstudio.com/updates/v1_63

**Comment by kitsonk** [comment]
I think the insiders build is daily, so the vscode fix should be in the next insiders build, so installing https://code.visualstudio.com/insiders/ might also work.  Hopefully we will figure out what the plan is for backporting soon.

**Comment by dojyorin** [comment]
It's tentative and a bit dirty, but I've implemented a workaround with VSCode 1.64.0.

ref. https://github.com/microsoft/vscode/issues/142139 and https://github.com/microsoft/vscode/commit/df09257f2e73fb382e2abe8a42d635fb33fe1d31

There's only one fix, but it's a bit troublesome to edit because it's bundled and minified at build time.

`(VSCode program root)\resources\app\extensions\typescript-language-features\dist\extension.js:1#500619`

```js
// Before
c.isWeb)()?t.uri.toString():t.uri.path)}

// After
c.isWeb)()?t.uri.toString():t.uri.fsPath)}
                               // ^ fix from "path" to "fsPath"
```

**Comment by kitsonk** [comment]
vscode 1.64.1 has been released with the fix included, users should update to 1.64.1.

**Comment by kitsonk** [comment]
Actually I was wrong... the fix isn't in 1.64.1, it is hopefully going to be in 1.64.2 (Recovery 2)

**Comment by lts20050703** [comment]
How is it possible that VSC Insider fix the issue before 1.64.1 release yet it's not in there?

**Comment by lucacasonato** [comment]
> How is it possible that VSC Insider fixed the issue way before 1.64.1 is released yet the fix is not in 1.64.1?

Best to ask the VS Code team this. They likely don't cut recovery releases from the main branch directly.

**Comment by dsherret** [comment]
Yup. I've also confirmed it's fixed in 1.64.2.

**Comment by nyuuke** [comment]
same styled components error problem in VScode 1.73.1

**Comment by shinebayar-g** [comment]
Still getting this.. Hmm 🤔

**Comment by khanakia** [comment]
I am still getting the error warning and tried everything installing, init and reloading etc.
![Screenshot 2023-02-11 at 7 40 51 PM](https://user-images.githubusercontent.com/2174170/218262523-7357e522-417f-4b87-a5fc-f1e72cf7b71e.png)

**Comment by shinebayar-g** [comment]
@khanakia checkout this setting https://github.com/denoland/vscode_deno/issues/66#issuecomment-1423255630

**Comment by khanakia** [comment]
@shinebayar-g Thanks it worked :)
