### ISSUE TITLE
Extension doesn't seem to do anything

### ISSUE THREAD

**Issue by brundonsmith** [denoland/vscode_deno#80]
I switched from one of the now-deprecated extensions, which was working, and this one isn't working properly. In fact, it seems to have all the same errors that you get with plain TypeScript and no Deno extension:

<img width="985" alt="main_ts_—_jlox_and_Issues_·_denoland_vscode_deno" src="https://user-images.githubusercontent.com/3674979/83954187-991b5280-a80c-11ea-9f85-1f794ed74dc7.png">

On the references to `Deno` it says `Cannot find name 'Deno'.`.

The extension is definitely active (I can see `Deno 1.0.5` in the corner) and I've restarted my editor, upgraded to the latest deno runtime, etc.

Edit: In case it matters, I'm on macOS

**Comment by thezanke** [comment]
I'm having the same problem

**Comment by thezanke** [comment]
I figured out how to get mine to work, I had to click the typescript version number down on the bottom right, click "Select Typescript Version" and then "Use VSCode's Version". Once I did that everything started working properly. Not sure how it got changed to use any other version but there you have it.

**Comment by brundonsmith** [comment]
I tried @thezanke's suggestion. It seemed like I was already using VSCode's version; either way, it didn't solve the problem

**Comment by bsunderhus** [comment]
I'm having the same issue. seems like the extension is simply not working, I'm developing in a devcontainer and it used to work fine with [axetroy](https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno) version. 🤷🏼‍♂️

**Comment by TTSKarlsson** [comment]
I can confirm, not working for minimal setup either. (Using VSCode builtin typescript 3.9.4)

![image](https://user-images.githubusercontent.com/9962943/83962852-4fc91280-a8a1-11ea-9bb5-8dd8394119b0.png)

**Comment by bsunderhus** [comment]
Using the [typescript-deno-plugin](https://github.com/justjavac/typescript-deno-plugin#configuration) solves the issue for me fortunately. Couldn't debug enough this extension to find the cause of this :(

**Comment by FaberVitale** [comment]
I did not have any issue with @axetroy version but this plugin doesn't work.

I have tried [this](https://github.com/denoland/vscode_deno/issues/80#issuecomment-640120756) but nothing has changed.

### pic

<img width="1792" alt="Screenshot 2020-06-07 at 10 21 35" src="https://user-images.githubusercontent.com/16583125/83963793-bf8ecb80-a8a8-11ea-969b-e3ce5fc01d89.png">

### setting.json

```json
 {
    "deno.enable": true,
    "editor.rulers": [80]
  }    
```

### Vscode

* version 1.45

**Comment by David-Else** [comment]
The new version of this extension was published to the Marketplace yesterday, but the update was not triggered by VS Code. 

Completely uninstall your current version, close and open VS Code to make sure the cached version is deleted, and re-install. Now you have the update! The version number was not updated.

Does this fix it?

**Comment by digitalclover** [comment]
I just installed the extension for the first time about an hour ago and experiencing the same issue. 

Similar to @bsunderhus, I installed `typescript-deno-plugin` along with a workspace version of TypeScript `v.3.9.5`. Changing back to VSCode version `v3.8.3` essentially disables the extension.

**Comment by bsunderhus** [comment]
Same here. I just installed this extension for the first today.

**Comment by David-Else** [comment]
I just checked, and now with the update the wrongly checking `.js` error is gone, but the extension is now is broken for me too.
![broken-code-deno](https://user-images.githubusercontent.com/12832280/83964987-6888f680-a8a8-11ea-9f4d-1a51c8f339a5.png)

**Comment by VictorLimou** [comment]
It's the same for me, I'm also on MacOS, using VSCode TypeScript version and i've installed this plugin for the first time today (uninstalling the "deprecated" one just before). 
I already try to reload VSC, disable/enable the plugin, however it just doesn't work for me.

**Comment by thezanke** [comment]
Okay, I ran into the issue again. What I had to do was:
```ssh
$ npm install -g typescript
```
and grab the path that it tells me it installed the bin files to, like `"/Users/thezanke/.nvm/versions/node/v13.12.0/lib/node_modules/typescript"` and use that in my vscode settings like:
```json
{
   "typescript.tsdk": "/Users/thezanke/.nvm/versions/node/v13.12.0/lib/node_modules/typescript/lib"
}
```
(note that I added `/lib` after `/typescript`)

_AND THEN_ I did what I mentioned earlier
> click the typescript version number down on the bottom right, click "Select Typescript Version" and then "Use VSCode's Version".

make sure you click it even if it looks like it's already selected.

This fixed it for me again, I didn't think the settings.json had anything to do with it so I reverted it and on my next restart it stopped working.

**Comment by elnobun** [comment]
I fixed this issue by first

`Upgrading to typescript 3.9.5`

Sadly, VScode still used `typescript 3.8.3`

In the `settings` I forced VScode to use the lastes type script

```
 "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib/"
```

Now its working as expected

<img width="611" alt="Screenshot 2020-06-07 at 17 06 57" src="https://user-images.githubusercontent.com/15114201/83973894-5b3c2e00-a8e1-11ea-9bf0-17e147fa74f0.png">

**Comment by melvin2016** [comment]
The extension doesn't do anything on macOS. No autocompletion. 🙁

**Comment by elnobun** [comment]
@melvin2016, I get autocompletion after everything was fixed as I desribed above. :)

**Comment by elnobun** [comment]
> The extension doesn't do anything on macOS. No autocompletion. 🙁

@melvin2016, I get autocompletion after everything was fixed as I desribed above. :)

**Comment by melvin2016** [comment]
> ### FIX (macOS)
> <img alt="Screenshot 2020-06-07 at 17 21 49" width="611" src="https://user-images.githubusercontent.com/15114201/83974221-a8210400-a8e3-11ea-888c-11488184d72a.png">
> 
> `Upgrade to latest typescript > 3.9.5` globally
> 
> Sadly, VScode still used `typescript 3.8.3`
> 
> In the `settings.json` file, force VScode to use the lastest typescript
> 
> ```
>  "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib/"
> ```
> 
> Now its working as expected
> 
> <img alt="Screenshot 2020-06-07 at 17 06 57" width="611" src="https://user-images.githubusercontent.com/15114201/83973894-5b3c2e00-a8e1-11ea-9bf0-17e147fa74f0.png">

Thanks, @elnobun It working now!

**Comment by brundonsmith** [comment]
Confirmed that @elnobun's fix worked for me

**Comment by andylei** [comment]
@elnobun's fix did not work for me unfortunately

**Comment by TTSKarlsson** [comment]
@elnobun's fix did not work for me either. (Both Windows and Linux Remote)

**Comment by Mejanhaque** [comment]
> ### FIX (macOS)
> <img alt="Screenshot 2020-06-07 at 17 21 49" width="611" src="https://user-images.githubusercontent.com/15114201/83974221-a8210400-a8e3-11ea-888c-11488184d72a.png">
> 
> `Upgrade to latest typescript > 3.9.5` globally
> 
> Sadly, VScode still used `typescript 3.8.3`
> 
> In the `settings.json` file, force VScode to use the lastest typescript
> 
> ```
>  "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib/"
> ```
> 
> Now its working as expected
> 
> <img alt="Screenshot 2020-06-07 at 17 06 57" width="611" src="https://user-images.githubusercontent.com/15114201/83973894-5b3c2e00-a8e1-11ea-9bf0-17e147fa74f0.png">

It worked for me in Windows 10... for those who installed typescript globally with npm package use the "C:\Users\<your username>\AppData\Roaming\npm\node_modules\typescript\lib" location

you can find your location here...
![image](https://user-images.githubusercontent.com/41269045/84015672-04e0f500-a99e-11ea-9ec9-db1e7b9a45c6.png)

**Comment by TTSKarlsson** [comment]
> 
> It worked for me in Windows 10... for those who installed typescript globally with npm package use the "C:\Users<your username>\AppData\Roaming\npm\node_modules\typescript\lib" location
@Mejanhaque , I think we all tried that. Are you sure you don't have a tsconfig.json that helps you out or other settings?

![image](https://user-images.githubusercontent.com/9962943/84016414-8d02d280-a97d-11ea-9098-9f58549f2472.png)

This setup does not work, as shown, with the denoland extension. (Windows 10)

**Comment by Mejanhaque** [comment]
> > It worked for me in Windows 10... for those who installed typescript globally with npm package use the "C:\Users\AppData\Roaming\npm\node_modules\typescript\lib" location
> 
> @Mejanhaque , I think we all tried that. Are you sure you don't have a tsconfig.json that helps you out or other settings?
> 
> ![image](https://user-images.githubusercontent.com/9962943/84016414-8d02d280-a97d-11ea-9098-9f58549f2472.png)
> 
> This setup does not work, as shown, with the denoland extension. (Windows 10)

No need tsconfig..check the sc below:
![image](https://user-images.githubusercontent.com/41269045/84024981-a2dbbc00-a9ac-11ea-99a1-056960b7e455.png)

**Comment by TTSKarlsson** [comment]
So strange that the exact same thing only works for a few people. Maybe it doesn't work on VSCode 1.46.0, because that's what I'm using.

**Comment by kosciej** [comment]
@TTSKarlsson I've got VSCode 1.45.1 and your approach (global tsdk) works on my MacOS. Previous (workspace) solution didn't work for me.

**Comment by AQUIN0S** [comment]
> ### FIX (macOS)
> <img alt="Screenshot 2020-06-07 at 17 21 49" width="611" src="https://user-images.githubusercontent.com/15114201/83974221-a8210400-a8e3-11ea-888c-11488184d72a.png">
> 
> `Upgrade to latest typescript > 3.9.5` globally
> 
> Sadly, VScode still used `typescript 3.8.3`
> 
> In the `settings.json` file, force VScode to use the lastest typescript
> 
> ```
>  "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib/"
> ```
> 
> Now its working as expected
> 
> <img alt="Screenshot 2020-06-07 at 17 06 57" width="611" src="https://user-images.githubusercontent.com/15114201/83973894-5b3c2e00-a8e1-11ea-9bf0-17e147fa74f0.png">

For those that used nvm to install node, it might be handy to note that the right directory is actually a slightly different path! The path you'll be looking for on MacOS would be "/Users/<username>/.nvm/versions/node/<default node version>/lib/node_modules/typescript/lib/"

**Comment by ry** [comment]
Hi Everyone,

I just want to write and say that we (Deno Land) haven't abandoned this extension module - we plan to work on these fixes - but as this is open source software, we just don't have the resources to address these problems immediately. We hope to dedicate some time to this extension next week after the Deno 1.1.0 release.

Ryan

**Comment by andyvanee** [comment]
For reference, if anyone is using [DevContainers](https://code.visualstudio.com/docs/remote/containers), I got the extension working by adding the extension to `devcontainer.json`:

```json
"extensions": ["denoland.vscode-deno"]
```

And then adding the full path to the lib directory in `.vscode/settings.json`:

```json
"typescript.tsdk": "/root/.vscode-server/extensions/denoland.vscode-deno-1.24.0/server/node_modules/typescript/lib"
```

**Comment by arantesxyz** [comment]
The extension doesn't work at all. I recommend you guys to use the "deprecated" (which looks to be less deprecated than the official) version: https://marketplace.visualstudio.com/items?itemName=justjavac.vscode-deno&ssr=false

**Comment by GustavoFenilli** [comment]
> For reference, if anyone is using [DevContainers](https://code.visualstudio.com/docs/remote/containers), I got the extension working by adding the extension to `devcontainer.json`:
> 
> ```json
> "extensions": ["denoland.vscode-deno"]
> ```
> 
> And then adding the full path to the lib directory in `.vscode/settings.json`:
> 
> ```json
> "typescript.tsdk": "/root/.vscode-server/extensions/denoland.vscode-deno-1.24.0/server/node_modules/typescript/lib"
> ```

Using WSL2 and didn't work for me, still getting the same error.

**Comment by pedropaulosuzuki** [comment]
I have the same issue on Ubuntu 20.04 LTS, while on Windows 10 everything works fine.

**Comment by scottjr632** [comment]
For those using WSL2.0, I got this plugin to work by globally installing the `typescript-deno-plugin` npm package and updating my typescript version with ` npm install -g typescript@latest`

My `tsconfig.json`
```
{
    "compilerOptions": {
        "plugins": [
            {
                "name": "typescript-deno-plugin",
                "enable": true,
                "importmap": "import_map.json"
            }
        ]
    }
}
```
And my settings.json
```
{
    "deno.enable": true,
    // this is the path to your globally installed typescript
    "typescript.tsdk": "/home/scott/.npm-global/lib/node_modules/typescript/lib"
}
```

I also had to click on the typescript version at the bottom right and select `use workspace version`

Hope this helps someone because I spent way too much time trying to get this to work.

**Comment by ry** [comment]
possibly fixed now

**Comment by Gumpie** [comment]
I have just updated to v1.25.0 and it seems to be working for me now.

**Comment by 8x13b** [comment]
macOS 13 High Sierra. Still broken.

**Comment by sushruth** [comment]
Issue is back on Windows as well currently with vscode@1.47.3 and this plugin @ 1.25.0

**Comment by rok-star** [comment]
<img width="155" alt="Screenshot 2020-09-05 at 14 53 08" src="https://user-images.githubusercontent.com/3323864/92304554-ba184e80-ef87-11ea-906e-8910a77d29ae.png">
<img width="124" alt="Screenshot 2020-09-05 at 14 52 49" src="https://user-images.githubusercontent.com/3323864/92304556-bd133f00-ef87-11ea-8feb-368565a8a504.png">

Can I manually import Deno's lib, like import { Deno } from '...'   ?

**Comment by lucacasonato** [comment]
Did you enable the extension by adding `"deno.enable": true` in the `.vscode/settings.json` file? See https://github.com/denoland/vscode_deno#usage

**Comment by MejanH** [comment]
> <img alt="Screenshot 2020-09-05 at 14 53 08" width="155" src="https://user-images.githubusercontent.com/3323864/92304554-ba184e80-ef87-11ea-906e-8910a77d29ae.png">
> 
> <img alt="Screenshot 2020-09-05 at 14 52 49" width="124" src="https://user-images.githubusercontent.com/3323864/92304556-bd133f00-ef87-11ea-8feb-368565a8a504.png">
> 
> Can I manually import Deno's lib, like import { Deno } from '...' ?

Yes, you can. but I don't think its working with vscode "import" snippets. But if you manually write like `import {} from "htt.."` then the modules start to show up like the official gif plugin says. And also remember to enable deno in your project directory. I wrote an article about deno intellisense on vscode. You can check out the link below.

[Deno Intellisense or Snippets for VS Code](https://alhaqi.com/blog/deno-intellisense-on-vscode)

**Comment by rok-star** [comment]
Yes, I correctly resolves imports like import * as Path from 'https://deno.land/std/path/mod.ts'; and Deno label is appeared in status bar

**Comment by lucacasonato** [comment]
What version of Deno are you using? What OS are you on? What VS Code version? What extension version?

**Comment by rok-star** [comment]
Deno 1.3.2
Catalina 10.15.6
Code 1.48.2

I also have this setting globally "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib",

**Comment by lucacasonato** [comment]
Did you restart VS Code after enabling the setting in `.vscode/settings.json`?

**Comment by rok-star** [comment]
I solved it!

Setting in workspace file is not respected.

I added .vscode/settings.json { "deno.enable": true } to the root folder, where my *.ts files are actually located.

**Comment by donaldoakes** [comment]
I wonder why this issue is closed. None of the workarounds described here succeeded for me on macOS Catalina with TypeScript 4.0.3.

**Comment by kitsonk** [comment]
@donaldoakes the causes of this issue simply cannot be causing the issue you are experiencing.  The issues that let to the opening of this are resolved (which is why the issue was closed).  Almost all of the work arounds listed here are for a very old version of the plugin and won't be useful with current versions.

If you are having issues with the extension, join the chat on Discord or open an issue with more details than this, like version of Visual Studio Code and the version of the extension installed.

**Comment by FSou1** [comment]
I made this work finally. 

I had to place the `.vscode/settings.json` to the root of the workspace:

```
{
    "deno.enable": true,
    "typescript.tsdk": "C:/Users/myuser/AppData/Roaming/npm/node_modules/typescript/lib"
}
```

**Comment by MichaelDebetaz** [comment]
**WSL2 Ubuntu, Deno 1.7.5, VS Code 1.53.2, JavaScript  and TypeScript Nightly 4.3.20210223**

Hi guys, I was screening this thread after installing Deno and its VS Code extension for the first time. I tried all that was mentionned above, but nothing worked. I was about to give up until I tried to downgrade from the current version (3.0.1) to the version 2.3.3.

Then I ran into the problem of deno not found in the $PATH, that was solved in [the issue #234](https://github.com/denoland/vscode_deno/issues/234#issuecomment-781093156) which proposed to create a symbolic link with:

> I had the same issue. I resolved it with:
> 
> * `sudo ln -s /home/losintikfos/.deno/bin/deno /usr/bin`
> * Restart vscode.

And it worked! Then I tried pushing my luck and updated The Deno extension again and everything finally worked.
