### ISSUE TITLE
Cache bug: 'missing field `uri`'

### ISSUE THREAD

**Issue by WorriedArrow** [denoland/vscode_deno#966]
**Describe the bug**

**To Reproduce**

1. Import a module that isn't cached in a Deno-enabled workspace, I used
`import { WebSocket, isWebSocketCloseEvent } from 'https://deno.land/std/ws/mod.ts';`
2. Go to Quick Fix -> Cache `https://deno.land/...` and its dependencies.
3. Message should pop up like the following: missing field \`uri`

**Expected behavior**

Just download and cache the module without error.

**Screenshots**

![image](https://github.com/denoland/vscode_deno/assets/81983357/34e88608-7e7f-4277-82ae-47f056f6fdd7)

**Versions**

vscode: 1.83.0 deno: 1.36.1 extension: 3.25.1

**Comment by ameesme** [comment]
Experiencing the same issue. Did you manage to resolve it since you closed the issue?

**Comment by WorriedArrow** [comment]
It appears that you just have to `deno run` the script with that first to cache it, reopening as it seems like an extension issue.

**Comment by WorriedArrow** [comment]
And the intended behavior is obviously for the extension to cache it on its own without `deno run`

**Comment by nayeemrmn** [comment]
This should be fixed in 1.37.x, can anyone reproduce on the latest version?

**Comment by ameesme** [comment]
Can confirm the issue appears to be resolved!

**Comment by matart15** [comment]
🤔  Still happening for me on v3.26.0

```ts
import Stripe from "npm:stripe@^11.16";
```

**Comment by matart15** [comment]
My bad. I had to reload my vscode few times after updating deno.

Error disappeared now. Thank you for the fix

**Comment by adamatat** [comment]
I just installed VSCode and this is still happening on v3.26.0.

```
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:57:32.750Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by adamatat** [comment]
Ping @nayeemrmn

**Comment by nayeemrmn** [comment]
@adamatat What's your Deno version? `deno --version`

**Comment by adamatat** [comment]
@nayeemrmn 

```
deno 1.33.2 (release, aarch64-apple-darwin)
v8 11.4.183.1
typescript 5.0.3
```

**Comment by adamatat** [comment]
@nayeemrmn I was on 1.33.2, never mind and thank you for your fast response.

**Comment by sturmenta** [comment]
For me the red lint disappears after run `deno check --all script.ts` and reloading the vscode
